
# 识别盔甲架名称
name-regex: '^\s*(?<id>.{0,24}?)\s*(?:区块加载|区块加载器)\s*(?<radius>\d+)\s*$'

# 命名牌没有匹配到新 id 则继承之前的命名
inherit-id: true

# 当 id 匹配器没有匹配到内容时使用的默认值
default-id: '未命名'

# 激活后盔甲架名称 %id% %radius% %time%
display-format: '%id% [区块加载器] %radius% - %time%'

# 过期后盔甲架名称 %id% %radius% %time%
expiry-format: '%id% [区块加载器] %radius% - %time%'

# 初始/累加时长
add-hours: 4

# 最大时长
max-hours: 24

# 最大加载半径
max-radius: 10

# 最大同时存在数量
max-count: 10

# 持久化设置
# true:  启动服务器后恢复之前活跃的加载器, 且在插件卸载时不释放区块
# false: 插件卸载时主动释放所有区块, 且在启动时清理残留的强加载区块
persistence: true

# 剩余时间低于指定小时数时执行指令
warn-hours: 2
# %world% %x% %y% %z% %name% %id% %radius% %time%
warn-commands:
  - 'say 区块加载器即将过期 [%world%/%x%/%y%/%z%] [%id%] %radius% - %time%'

# 维度显示名称
# 如果有定义, 那么 %world% 变量将使用对应的显示名称, 否则使用默认的维度名
world-names:
  world: '主世界'
  world_nether: '地狱'
  world_the_end: '末地'

msg:
  activate: '§bIpacEL §f> §a区块加载器已激活'
  quant-limit: '§bIpacEL §f> §b区块加载器达到数量限制'
  list-header: '§bIpacEL §f> §a活跃加载器列表:'
  list-line: '  §7- [%world%/%x%/%y%/%z%] [%id%] %radius% - %time%' # %world% %x% %y% %z% %name% %id% %radius% %time%
  list-hover: '点击传送'
