name: IpacChunkLoader
version: '${project.version}'
main: io.github.aplini.ipacChunkLoader.IpacChunkLoader
api-version: '1.21'
authors: [ ApliNi ]
website: https://github.com/aplini/

commands:
  icl:
    description: IpacChunkLoader 插件的主命令
    usage: /<command>

permissions:

  IpacChunkLoader.reload:
    description: '重载插件'
    default: op
  IpacChunkLoader.list:
    description: '查看活跃加载器列表'
    default: op
  IpacChunkLoader.clear:
    description: '清理所有强加载区块和加载器'
    default: op
  IpacChunkLoader.tp:
    description: '传送至活跃加载器'
    default: op
